on:
  push:
    branches:
      - develop
    name: Publish on BrainServer
jobs:
 FTP-Deploy-Action:
   name: FTP-Deploy-Action
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@master
     with:
       fetch-depth: 2
   - name: FTP-Deploy-Action
     uses: SamKirkland/FTP-Deploy-Action@v3.1.2-patch
     with:
       ftp-server: ftp://ftp.brainserver.synology.me/docker/Node/Strapi
       ftp-username: luca.pagot
       ftp-password: 1q"W£E$R%
       git-ftp-args: --insecure
